// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }

    dependencies {
        classpath libs.gradle
        classpath libs.google.services
        classpath libs.firebase.crashlytics.gradle
        classpath libs.org.jacoco.core
        classpath libs.kotlin.gradle.plugin
        classpath libs.sonarqube.gradle.plugin
        classpath libs.spotless.plugin.gradle

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

plugins {
    alias(libs.plugins.compose.compiler) apply false
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}

tasks.register('installGitHooks', Copy) {
    group = "development"
    def sourceFolder = "${rootProject.projectDir}/bin/githooks"
    def destFolder = "${rootProject.projectDir}/.git/hooks"

    description = "install git hooks"

    from(sourceFolder) {
        include '*'
    }
    into destFolder

    eachFile { file ->
        println "${sourceFolder}/${file.relativeSourcePath} -> ${destFolder}/${file.path}"
    }
}

tasks.register('emptyMediaStore', Exec) {
    commandLine 'adb', 'shell', 'content delete --uri content://media/external/images/media --where "1"'
}

def gitHubAction() {
    /*
     when running in a GitHub Action...
     ./gradlew --no-configuration-cache -PgitHubAction :app:connectedFdroidDebugAndroidTest
     */
    def value = project.getProperties().get("gitHubAction") != null ? "true": "false"
    println 'gitHubAction=' + value
    return value
}
